// Ordered list mirroring the sidebar — used to compute the first route a user
// can access when their default landing page is denied.
export const ACCESS_ROUTES: { perm: string; url: string }[] = [
  { perm: "dashboard_gp", url: "/dashboard" },
  { perm: "requisicao_colaboradores", url: "/requisicao-pessoal" },
  { perm: "processos_seletivos", url: "/processos-seletivos" },
  { perm: "funcionarios", url: "/funcionarios" },
  { perm: "mapa_funcionarios", url: "/mapa-funcionarios" },
  { perm: "avaliacoes_desempenho", url: "/avaliacoes-desempenho" },
  { perm: "ferramentas", url: "/patrimonio/ferramentas" },
  { perm: "dashboard_ssos", url: "/engenharia/dashboard" },
  { perm: "dashboard_medicoes", url: "/engenharia/dashboard-medicoes" },
  { perm: "plano_manutencao", url: "/engenharia/plano-manutencao" },
  { perm: "base_conhecimento", url: "/engenharia/base-conhecimento" },
  { perm: "solicitacao_servicos", url: "/engenharia/solicitacao-servicos" },
  { perm: "ordem_servico", url: "/engenharia/ordem-servico" },
  { perm: "rdo", url: "/engenharia/rdo" },
  { perm: "cronograma", url: "/engenharia/cronograma" },
  { perm: "eventograma", url: "/engenharia/eventograma" },
  { perm: "medicoes", url: "/engenharia/medicoes" },
  { perm: "bim", url: "/obras/bim" },
  { perm: "sco", url: "/orcamentos" },
  { perm: "dashboard_compras", url: "/compras/dashboard" },
  { perm: "requisicoes_compras", url: "/compras/requisicoes" },
  { perm: "cotacoes", url: "/compras/cotacoes" },
  { perm: "pedidos_compra", url: "/compras/pedidos" },
  { perm: "recebimento", url: "/compras/recebimento" },
  { perm: "estoque", url: "/compras/estoque" },
  { perm: "pregao", url: "/compras/pregao" },
  { perm: "licitacoes", url: "/licitacoes" },
  { perm: "juridico", url: "/juridico" },
  { perm: "comunicacao_mensagens", url: "/comunicacao/mensagens" },
  { perm: "comunicacao_avisos", url: "/comunicacao/avisos" },
  { perm: "comunicacao_notificacoes", url: "/comunicacao/notificacoes" },
  { perm: "comunicacao_whatsapp", url: "/comunicacao/whatsapp" },
  { perm: "pmoc", url: "/pmoc" },
  { perm: "evidencias", url: "/qualidade/evidencias" },
  { perm: "checklists", url: "/qualidade/checklists" },
  { perm: "chat_duda", url: "/chat-duda" },
  { perm: "financeiro.dashboard", url: "/financeiro/dashboard" },
  { perm: "financeiro.contas_pagar", url: "/financeiro/contas-pagar" },
  { perm: "financeiro.contas_receber", url: "/financeiro/contas-receber" },
  { perm: "monitor_tv", url: "/monitor-tv" },
  { perm: "gerencial_dashboard", url: "/gerencial/dashboard" },
  { perm: "gerencial_mapa_clientes", url: "/gerencial/mapa-clientes" },
  { perm: "gerencial_relatorios", url: "/gerencial/relatorios" },
  { perm: "gerencial_multidim", url: "/gerencial/multidimensional" },
  { perm: "empresa", url: "/empresa" },
  { perm: "clientes", url: "/clientes" },
  { perm: "fornecedores", url: "/fornecedores" },
  { perm: "equipamentos", url: "/cadastros/equipamentos" },
  { perm: "cargos", url: "/cargos" },
  { perm: "categorias_servicos", url: "/cadastros/categorias-servicos" },
  { perm: "servicos", url: "/cadastros/servicos" },
  { perm: "responsaveis_tecnicos", url: "/cadastros/responsaveis-tecnicos" },
  { perm: "materiais_servicos", url: "/compras/materiais" },
  { perm: "categorias_compras", url: "/compras/categorias" },
  { perm: "fabricantes", url: "/compras/fabricantes" },
  { perm: "usuarios", url: "/usuarios" },
  { perm: "perfis_acesso", url: "/perfis-acesso" },
  { perm: "auditoria", url: "/auditoria" },
];


