// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/listar-clientes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function textResult(payload) {
  return { content: [{ type: "text", text: JSON.stringify(payload) }] };
}
function errorResult(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function requireAuth(ctx) {
  return ctx.isAuthenticated() ? null : errorResult("N\xE3o autenticado.");
}

// src/lib/mcp/tools/listar-clientes.ts
var listar_clientes_default = defineTool({
  name: "listar_clientes",
  title: "Listar clientes",
  description: "Lista os clientes cadastrados no SGM, com filtro opcional por nome ou CNPJ.",
  inputSchema: {
    busca: z.string().optional().describe("Texto para filtrar por nome, nome fantasia ou CNPJ."),
    limite: z.number().int().min(1).max(100).optional().describe("M\xE1ximo de registros (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ busca, limite }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let q = supabaseForUser(ctx).from("clientes").select("id,nome,nome_fantasia,cnpj,cidade,uf,email,telefone_celular").limit(limite ?? 25);
    if (busca) q = q.or(`nome.ilike.%${busca}%,nome_fantasia.ilike.%${busca}%,cnpj.ilike.%${busca}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult({ total: data?.length ?? 0, clientes: data ?? [] });
  }
});

// src/lib/mcp/tools/listar-ordens-servico.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var listar_ordens_servico_default = defineTool2({
  name: "listar_ordens_servico",
  title: "Listar ordens de servi\xE7o",
  description: "Lista Ordens de Servi\xE7o (OS) do SGM, com filtros opcionais por n\xFAmero e status.",
  inputSchema: {
    numero: z2.string().optional().describe("N\xFAmero da OS (ex.: 16 ou 16-2026)."),
    status: z2.string().optional().describe("Status/situa\xE7\xE3o da OS."),
    limite: z2.number().int().min(1).max(100).optional().describe("M\xE1ximo de registros (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ numero, status, limite }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let q = supabaseForUser(ctx).from("ordens_servico").select("*").order("created_at", { ascending: false }).limit(limite ?? 25);
    if (numero) q = q.eq("numero", Number(String(numero).split("-")[0]));
    if (status) q = q.ilike("status", `%${status}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult({ total: data?.length ?? 0, ordens: data ?? [] });
  }
});

// src/lib/mcp/tools/listar-solicitacoes-servico.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var listar_solicitacoes_servico_default = defineTool3({
  name: "listar_solicitacoes_servico",
  title: "Listar solicita\xE7\xF5es de servi\xE7o",
  description: "Lista Solicita\xE7\xF5es de Servi\xE7o (SS) do SGM, com filtros opcionais por n\xFAmero e status.",
  inputSchema: {
    numero: z3.string().optional().describe("N\xFAmero da SS (ex.: 12 ou 12-2026)."),
    status: z3.string().optional().describe("Status/situa\xE7\xE3o da SS."),
    limite: z3.number().int().min(1).max(100).optional().describe("M\xE1ximo de registros (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ numero, status, limite }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let q = supabaseForUser(ctx).from("solicitacoes_servicos").select("*").order("created_at", { ascending: false }).limit(limite ?? 25);
    if (numero) q = q.eq("numero", Number(String(numero).split("-")[0]));
    if (status) q = q.ilike("status", `%${status}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult({ total: data?.length ?? 0, solicitacoes: data ?? [] });
  }
});

// src/lib/mcp/tools/listar-requisicoes-compras.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var listar_requisicoes_compras_default = defineTool4({
  name: "listar_requisicoes_compras",
  title: "Listar requisi\xE7\xF5es de compras (RCS)",
  description: "Lista Requisi\xE7\xF5es de Compras e Servi\xE7os (RCS/RC) do SGM, com filtros opcionais.",
  inputSchema: {
    numero: z4.string().optional().describe("N\xFAmero da RCS."),
    status: z4.string().optional().describe("Status da requisi\xE7\xE3o."),
    incluir_itens: z4.boolean().optional().describe("Quando verdadeiro, inclui os itens da requisi\xE7\xE3o."),
    limite: z4.number().int().min(1).max(100).optional().describe("M\xE1ximo de registros (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ numero, status, incluir_itens, limite }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const colunas = incluir_itens ? "id,numero,status,urgencia,centro_custo_nome,solicitante,created_at,itens" : "id,numero,status,urgencia,centro_custo_nome,solicitante,created_at";
    let q = supabaseForUser(ctx).from("requisicoes_compras").select(colunas).order("created_at", { ascending: false }).limit(limite ?? 25);
    if (numero) q = q.eq("numero", numero);
    if (status) q = q.ilike("status", `%${status}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult({ total: data?.length ?? 0, requisicoes: data ?? [] });
  }
});

// src/lib/mcp/tools/listar-funcionarios.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^3.25.76";
var listar_funcionarios_default = defineTool5({
  name: "listar_funcionarios",
  title: "Listar funcion\xE1rios",
  description: "Lista o quadro de funcion\xE1rios cadastrados no SGM, com busca opcional por nome ou CPF.",
  inputSchema: {
    busca: z5.string().optional().describe("Texto para filtrar por nome ou CPF."),
    limite: z5.number().int().min(1).max(100).optional().describe("M\xE1ximo de registros (padr\xE3o 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ busca, limite }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let q = supabaseForUser(ctx).from("funcionarios").select("id,nome,cpf,cargo_id,cliente_id,situacao,data_admissao").limit(limite ?? 25);
    if (busca) q = q.or(`nome.ilike.%${busca}%,cpf.ilike.%${busca}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    return textResult({ total: data?.length ?? 0, funcionarios: data ?? [] });
  }
});

// src/lib/mcp/tools/consultar-estoque.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z6 } from "npm:zod@^3.25.76";
var consultar_estoque_default = defineTool6({
  name: "consultar_estoque",
  title: "Consultar estoque",
  description: "Consulta as movimenta\xE7\xF5es de estoque do SGM e retorna o saldo calculado por material.",
  inputSchema: {
    material: z6.string().optional().describe("Nome (parcial) do material a consultar."),
    limite: z6.number().int().min(1).max(500).optional().describe("M\xE1ximo de movimenta\xE7\xF5es lidas (padr\xE3o 300).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ material, limite }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let q = supabaseForUser(ctx).from("estoque_movimentacoes").select("material_nome,tipo,quantidade,local_nome").limit(limite ?? 300);
    if (material) q = q.ilike("material_nome", `%${material}%`);
    const { data, error } = await q;
    if (error) return errorResult(error.message);
    const saldos = {};
    for (const m of data ?? []) {
      const chave = m.material_nome ?? "\u2014";
      const qtd = Number(m.quantidade ?? 0);
      const tipo = String(m.tipo ?? "").toLowerCase();
      saldos[chave] = (saldos[chave] ?? 0) + (tipo.includes("said") || tipo.includes("baixa") ? -qtd : qtd);
    }
    return textResult({
      movimentacoes_lidas: data?.length ?? 0,
      saldos: Object.entries(saldos).map(([material_nome, saldo]) => ({ material_nome, saldo }))
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "vdjezhhrnksluzealfcl";
var mcp_default = defineMcp({
  name: "lasant-sgm-4-0",
  title: "Lasant SGM 4.0",
  version: "0.1.0",
  instructions: "Ferramentas somente-leitura do SGM (Sistema de Gest\xE3o e Manuten\xE7\xE3o da Lasant): clientes, ordens de servi\xE7o (OS), solicita\xE7\xF5es de servi\xE7o (SS), requisi\xE7\xF5es de compras (RCS), funcion\xE1rios e estoque. Use-as para consultar dados reais do sistema; nunca invente registros.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    listar_clientes_default,
    listar_ordens_servico_default,
    listar_solicitacoes_servico_default,
    listar_requisicoes_compras_default,
    listar_funcionarios_default,
    consultar_estoque_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
