
CREATE TABLE public.funcionarios (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  nome TEXT NOT NULL,
  cpf TEXT NOT NULL,
  rg TEXT DEFAULT '',
  orgao_emissor TEXT DEFAULT '',
  data_nascimento TEXT DEFAULT '',
  sexo TEXT DEFAULT '',
  estado_civil TEXT DEFAULT '',
  nacionalidade TEXT DEFAULT 'Brasileira',
  naturalidade TEXT DEFAULT '',
  nome_mae TEXT DEFAULT '',
  nome_pai TEXT DEFAULT '',
  telefone TEXT DEFAULT '+55 ',
  email TEXT DEFAULT '',
  pcd BOOLEAN DEFAULT false,
  tipo_pcd TEXT DEFAULT '',
  cep TEXT DEFAULT '',
  logradouro TEXT DEFAULT '',
  numero TEXT DEFAULT '',
  complemento TEXT DEFAULT '',
  bairro TEXT DEFAULT '',
  cidade TEXT DEFAULT '',
  uf TEXT DEFAULT '',
  cargo_id TEXT DEFAULT '',
  cliente_id TEXT DEFAULT '',
  data_admissao TEXT DEFAULT '',
  data_demissao TEXT DEFAULT '',
  tipo_contrato TEXT DEFAULT 'CLT',
  salario TEXT DEFAULT '',
  jornada_trabalho TEXT DEFAULT '',
  ctps TEXT DEFAULT '',
  serie_ctps TEXT DEFAULT '',
  pis TEXT DEFAULT '',
  banco TEXT DEFAULT '',
  agencia TEXT DEFAULT '',
  conta TEXT DEFAULT '',
  tipo_conta TEXT DEFAULT 'Corrente',
  chave_pix TEXT DEFAULT '',
  titulo_eleitor TEXT DEFAULT '',
  zona_eleitoral TEXT DEFAULT '',
  secao_eleitoral TEXT DEFAULT '',
  cnh TEXT DEFAULT '',
  categoria_cnh TEXT DEFAULT '',
  validade_cnh TEXT DEFAULT '',
  certificado_reservista TEXT DEFAULT '',
  tamanho_camisa TEXT DEFAULT '',
  tamanho_calca TEXT DEFAULT '',
  tamanho_calcado TEXT DEFAULT '',
  peso TEXT DEFAULT '',
  altura TEXT DEFAULT '',
  passagens JSONB DEFAULT '[]'::jsonb,
  dependentes JSONB DEFAULT '[]'::jsonb,
  epis JSONB DEFAULT '[]'::jsonb,
  nrs JSONB DEFAULT '[]'::jsonb,
  observacoes TEXT DEFAULT '',
  status TEXT DEFAULT 'Ativo',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.funcionarios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all access to funcionarios" ON public.funcionarios
  FOR ALL USING (true) WITH CHECK (true);
